<?php
namespace app\components\Widgets;

use yii\base\Widget;

class Menu extends Widget
{
    public $activateItems = '1111';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run(){
        return $this->render("Menu",array('activateItems'=>$this->activateItems));
    }
}